import { Hono } from 'hono';

const th = new Hono();

type MessageItem = {
  messageId: string;
  message: string;
};

const baseContractResponse = {
  errors: [] as MessageItem[],
  warnings: [
    {
      messageId: 'TH-WARN-001',
      message: 'Mock response generated from test data.',
    },
  ],
  infos: [
    {
      messageId: 'TH-INFO-001',
      message: 'Contract payload is a non-production sample.',
    },
  ],
  data: {
    contractId: 0,
    isDraft: true,
    location: {
      locationId: 110,
      extName: 'Bangkok HQ',
      locationType: 'CITY',
    },
    operatingUnit: {
      partyId: 9001,
      partyNo: 9001,
      reference: 'TH-OU-001',
      extName: 'BMW Financial Services Thailand',
    },
    product: {
      productId: 701,
      productCode: 'TH-LEASE',
      extName: 'Thailand Lease Product',
    },
    program: {
      programId: 81,
      programCode: 'PRG-TH-STD',
      lookupName: 'TH_STANDARD',
      extName: 'TH Standard Program',
    },
    calcDt: '2026-06-26T07:57:52.129Z',
    inputDt: '2026-06-26T07:57:52.129Z',
    matureDt1: '2027-06-26T07:57:52.129Z',
    matureDt2: '2028-06-26T07:57:52.129Z',
    financialAssets: [
      {
        assetId: 10001,
        assetName: 'BMW 330e M Sport',
        assetType: {
          assetTypeId: 1,
          assetTypePath: 'Vehicle/Passenger',
          assetTypeName: 'Passenger Vehicle',
        },
        amtFinancedTotal: 1650000,
        taxesAmt: 115500,
        supplier: {
          partyId: 3001,
          partyNo: 3001,
          reference: 'TH-DEALER-3001',
          extName: 'Bangkok Autohaus',
        },
        supplierAddresses: [
          {
            county: { locationId: 1, extName: 'Bang Rak', locationType: 'COUNTY' },
            countryRegion: { locationId: 66, extName: 'Thailand', locationType: 'COUNTRY' },
            stateProvince: { locationId: 10, extName: 'Bangkok', locationType: 'PROVINCE' },
            city: { locationId: 110, extName: 'Bangkok', locationType: 'CITY' },
            zipCode: '10500',
            suburb: 'Silom',
            street: '123 Sathorn Road',
            isOverrideTaxArea: false,
            isDefaultAddress: true,
            addressId: 501,
            addressType: 'BUSINESS',
            alternateSuburb: 'Sathon',
            effectDtFrom: '2026-01-01T00:00:00.000Z',
            effectDtTo: '2099-12-31T00:00:00.000Z',
            isCurrent: true,
            addressComponentTemplateHdrId: 12,
            addressComponents: [
              { type: 'BUILDING', value: 'AIA Sathorn Tower' },
              { type: 'FLOOR', value: '19' },
            ],
          },
        ],
        assetDealType: 1,
        cost: 1650000,
        stockCode: 'TH-STK-330E-001',
        serialNo: 'SERIAL-330E-TH-001',
        assetDescription: 'BMW 330e M Sport test vehicle',
        manufacturer: {
          partyId: 4001,
          partyNo: 4001,
          reference: 'BMW-AG',
          extName: 'BMW AG',
        },
        colour: 'Alpine White',
        yearOfManufacture: 2026,
        isAssetCheckRequired: true,
        isTerminated: false,
        terminatedDt: null,
        amtTotalMsrp: 1890000,
        assetBalance: {
          assetBalanceId: 7001,
          effectiveDt: '2026-06-26T07:57:52.129Z',
          grossUnpaidReceivableAmt: 1450000,
          liabilityAmt: 1450000,
          averageExposureAmt: 980000,
          overdueDays: 0,
          futureAmt: 250000,
          futureChargesAmt: 15000,
          interestAccrued: 4200,
          arrearsAmt: 0,
          chargingBalance: 1454200,
          accruedDepreciation: 190000,
          totalPrincipal: 1300000,
          totalInterestAccruedAmt: 4200,
          totPricingIntAccruedAmt: 3800,
          grossUnpaidResidualAmt: 320000,
          adjustedBalLessNBV: 12000,
          customAmt00: 0,
          customAmt01: 0,
          customAmt02: 0,
          customAmt03: 0,
          customAmt04: 0,
          customAmt05: 0,
          customAmt06: 0,
          customAmt07: 0,
          customAmt08: 0,
          customAmt09: 0,
          customDt00: '2026-06-26T07:57:52.129Z',
          customDt01: '2026-06-26T07:57:52.129Z',
          customDt02: '2026-06-26T07:57:52.129Z',
          customDt03: '2026-06-26T07:57:52.129Z',
          customDt04: '2026-06-26T07:57:52.129Z',
          amtOverduePrincipal: 0,
          amtDeficiencyOutstandingBalance: 0,
          residualAmt: 320000,
          financialAssetId: 10001,
        },
        assetMeters: [
          {
            cpuMeterId: 1,
            meterTypeId: 1,
            name: 'ODO',
            reference: 'KM',
            units: 'km',
            startReading: 0,
            lastReadingDt: '2026-06-26T07:57:52.129Z',
            lastReadingUsage: 15500,
          },
        ],
        financialAssetLease: {
          scheduleTerm: 60,
          startDt: '2026-01-01T00:00:00.000Z',
          matureDt: '2030-12-31T00:00:00.000Z',
          pctResidualValue: 22,
          residualValue: 363000,
          residualValueDelayDt: '2030-12-31T00:00:00.000Z',
          pctBalloon: 5,
          amtBalloon: 82500,
          balloonDt: '2030-12-31T00:00:00.000Z',
          amtFinancedTotal: 1650000,
          totalAmtFinancedTax: 115500,
          amtBaseRepayment: 29000,
          amtTotalInterest: 175000,
          totalAmtInterestTax: 12250,
          amtRecommendedRetailPriceCost: 1890000,
          amtTotalMsrp: 1890000,
          financialAssetPriceSegments: [
            {
              priceSegmentId: 1,
              priceScheduleId: 1,
              segmentNo: 1,
              calcDt: '2026-06-26T07:57:52.129Z',
              amtSegment: 29000,
              amtSegmentGross: 31030,
              isCustomised: false,
              isInterestOnly: false,
              isPrincipalOnly: false,
              proportion: 1,
              installments: 60,
              installmentFrequency: 'MONTHLY',
              segmentType: 'STANDARD',
              changeAction: 'NONE',
            },
          ],
          assetRvComponents: {
            pctRvBaseComponent: 20,
            amtRvBaseComponent: 330000,
            pctRvSubsidyComponent: 2,
            amtRvSubsidyComponent: 33000,
          },
          customFields: [{ name: 'salesChannel', value: 'dealer', customFieldDataType: 'string' }],
          customFieldGroups: [
            {
              name: 'pricingFlags',
              items: [{ rowNo: 1, customFields: [{ name: 'promoCode', value: 'THQ2', customFieldDataType: 'string' }], changeAction: 'NONE' }],
            },
          ],
          isTaxBasedPricing: true,
          financialAssetMeterUsages: [
            {
              assetMeterUsageId: 1,
              cpuMeterName: 'ODO',
              expectedUsageBasis: 'TERM_TOTAL',
              expectedUsage: 100000,
              excessGrace: 1000,
              excessCurve: 0,
              startUsage: 0,
              currentReading: 15500,
              additionalUsage: 0,
              totalUsage: 15500,
              excessUsage: 0,
              finalUsageReading: 100000,
            },
          ],
          ppuAssetExpectedUsages: [],
          ppuAssetExpectedUsageAdjs: [],
          ppuAssetOverUsageRates: [],
        },
      },
    ],
    hasPendingRestructure: false,
    isRegulated: true,
    isRegulatedProdOverridden: false,
    regulatedLastUpdatedByUserId: 101,
    regulatedLastUpdatedByUserName: 'th.mock.user',
    additionalNotes: 'TH contract mock payload for integration testing',
    alternativeReference: 'ALT-TH-1234',
    reference: 'TH-CTR-1234',
    calculationMode: 'STANDARD',
    amtFinanced: 1650000,
    isTaxInclusive: true,
    firstInstallmentDt: '2026-07-05T00:00:00.000Z',
    installmentFrequency: 'MONTHLY',
    installmentTiming: 'ARREARS',
    eomCycling: false,
    marginRate: 3.2,
    cofRate1: 1.7,
    lessorRate: 4.9,
    compoundFrequency: 'MONTHLY',
    externalCompoundFrequency: 'MONTHLY',
    contractState: 'ACTIVE',
    creditState: 'APPROVED',
    businessModel: 'LEASE',
    currency: { id: 764, name: 'Thai Baht', code: 'THB' },
    aiiExternalReferences: [],
    contractPartyRoles: [
      {
        contractPartyId: 1,
        party: { partyId: 2001, partyNo: 2001, reference: 'CUST-2001', extName: 'Somsak Chaiyaporn' },
        partyRole: 'CUSTOMER',
        seqNo: 1,
        changeAction: 'NONE',
      },
    ],
    flows: [],
    taxProfile: { id: 1, name: 'TH VAT 7%', code: 'TH_VAT_7' },
    opportunity: { opportunityId: 7701, reference: 'OPP-TH-7701', name: 'Bangkok lease 330e' },
    locationDependentContractRevision: 'REV-1',
    businessUnit: { partyId: 9100, partyNo: 9100, reference: 'BU-TH', extName: 'Thailand BU' },
    customerParty: { partyId: 2001, partyNo: 2001, reference: 'CUST-2001', extName: 'Somsak Chaiyaporn' },
    customerPartyAccount: { partyAccountId: 6001, partyId: 2001, accountNo: 'ACC-TH-2001', name: 'Primary customer account', partyNo: 2001 },
    dealer: { partyId: 3001, partyNo: 3001, reference: 'TH-DEALER-3001', extName: 'Bangkok Autohaus' },
    dealerPartyAccount: { partyAccountId: 6101, partyId: 3001, accountNo: 'ACC-DEALER-3001', name: 'Dealer settlement account', partyNo: 3001 },
    broker: { partyId: 0, partyNo: 0, reference: '', extName: '' },
    coBorrowers: [],
    vendor: { partyId: 3001, partyNo: 3001, reference: 'TH-DEALER-3001', extName: 'Bangkok Autohaus' },
    customFlowHdrId: 0,
    customFlows: [],
    customFields: [{ name: 'sourceSystem', value: 'mock-th-api', customFieldDataType: 'string' }],
    customFieldGroups: [],
    leaseDetails: {
      isStructured: false,
      advInstallmentsInitial: 0,
      advInstallmentsFinal: 0,
      advInstallmentsInitialExp: false,
      advInstallmentsInitialRecd: false,
      advInstallmentsFinalExp: false,
      advInstallmentsFinalRecd: false,
    },
    loanAccountDetails: {
      amtBalloon: 82500,
      balloonDt: '2030-12-31T00:00:00.000Z',
      pctBalloon: 5,
      originalLoanAmt: 1650000,
      amtDrawdownLimit: 1650000,
      scheduledTerm: 60,
      contractPriceSegments: [],
      eventPlanner: [],
    },
    refundDetails: {
      cashflowReleaseDt: '2026-06-26T07:57:52.129Z',
      paymentInstructionId: 0,
      payeeReference: 'CUST-2001',
      paymentReference: 'RF-TH-1234',
      amtRefund: 0,
    },
    contractPostingRulesAttribute: {
      postingRulesAttribute: {
        postingRulesAttributeId: 1,
        code: 'TH-POST-DEFAULT',
        name: 'TH Posting Default',
        extName: 'TH Posting Default',
      },
      effectiveDt: '2026-06-26T07:57:52.129Z',
      isRestructure: false,
    },
    contractFull: {
      customerPartyDetails: {
        partyNo: 2001,
        partyId: 2001,
        name: 'Somsak Chaiyaporn',
        partyType: ['INDIVIDUAL'],
        operatingUnit: { partyId: 9001, partyNo: 9001, reference: 'TH-OU-001', extName: 'BMW Financial Services Thailand' },
        businessUnit: { partyId: 9100, partyNo: 9100, reference: 'BU-TH', extName: 'Thailand BU' },
        owner: { partyId: 9001, partyNo: 9001, reference: 'TH-OU-001', extName: 'BMW Financial Services Thailand' },
        taxCertificateType: 'NONE',
        preventOverdueInterest: false,
        reference: 'CUST-2001',
        phoneHome: '021234567',
        phoneMobile: '0812345678',
        phoneBusiness: '',
        phoneBusinessExtension: '',
        pager: '',
        faxBusiness: '',
        faxHome: '',
        webPage: '',
        emailHome: 'somsak@example.com',
        emailBusiness: '',
        emailOther: '',
        preferredContactMethod: 'MOBILE',
        extName: 'Somsak Chaiyaporn',
        code: 'CUST-2001',
        taxNo: 'TH-TAX-2001',
        alternateName: '',
        incorporationLocation: { locationId: 66, extName: 'Thailand', locationType: 'COUNTRY' },
        invoiceName: 'Somsak Chaiyaporn',
        isTaxExempt: false,
        taxExemptCertificate: '',
        taxExemptCertificateEffDt: '2026-06-26T07:57:52.130Z',
        dunsNumber: '',
        preferredLanguage: 'th',
        partyStatus: 'ACTIVE',
        tradingAs: '',
        doNotSolicit: false,
        isRegForSalesTaxPayments: true,
        isPreventLateFee: false,
        isAllowLateFeesOverride: true,
        isAllowOverdueInterestOverride: true,
        isSelfServiceAccountActive: true,
        businessIndividual: 'INDIVIDUAL',
        businessPartyDetail: {
          businessRefNo: '',
          businessRefNo2: '',
          businessRefNo3: '',
          industrySchema: { id: 0, name: '', code: '' },
          industry: { id: 0, name: '', code: '' },
          employees: 0,
          tickerSymbol: '',
          stockExchange: '',
          marketCapitalisation: 0,
          lengthInBusiness: '',
          accountReceived: false,
          establishedDt: '2026-06-26T07:57:52.130Z',
          entityType: '',
        },
        individualPartyDetail: {
          title: 'Mr',
          firstNames: 'Somsak',
          middleName: '',
          nationalNo: 'TH-ID-2001',
          dateOfBirth: '1990-01-01T00:00:00.000Z',
          gender: 'MALE',
          maritalStatus: 'SINGLE',
          nationality: { locationId: 66, extName: 'Thailand', locationType: 'COUNTRY' },
          ethnicity: '',
          driversLicenseNo: 'DL-TH-2001',
          driversLicenseExpiryDt: '2030-01-01T00:00:00.000Z',
          driversLicenseLocation: { locationId: 10, extName: 'Bangkok', locationType: 'PROVINCE' },
          homeOwnerStatus: 'RENT',
          passportLocation: { locationId: 66, extName: 'Thailand', locationType: 'COUNTRY' },
          passportNo: '',
          passportExpiryDt: '2026-06-26T07:57:52.130Z',
          identificationRef1: '',
          identificationRef2: '',
          isDeceased: false,
          deceasedDate: '2026-06-26T07:57:52.130Z',
          suffix: '',
        },
        customFields: [],
        customFieldGroups: [],
        taxTypeExemptions: [],
        regulatoryClassification: 'STANDARD',
        isOverrideRegulatoryClass: false,
        aiiExternalReferences: [],
        partyPrivacyOptions: [],
        partyContactPreference: {
          businessPreference: { contactType: 'EMAIL', availableDayTime: [], unavailableDayTime: [], preferredTimeZone: 'Asia/Bangkok' },
          homePreference: { contactType: 'MOBILE', availableDayTime: [], unavailableDayTime: [], preferredTimeZone: 'Asia/Bangkok' },
          otherPreference: { contactType: 'NONE', availableDayTime: [], unavailableDayTime: [], preferredTimeZone: 'Asia/Bangkok' },
        },
      },
      supplier: { partyId: 3001, partyNo: 3001, reference: 'TH-DEALER-3001', extName: 'Bangkok Autohaus' },
      supplierPartyAccount: { partyAccountId: 6101, partyId: 3001, accountNo: 'ACC-DEALER-3001', name: 'Dealer settlement account', partyNo: 3001 },
      contractTags: [{ tagId: 1, isActive: true, tagName: 'TH-MOCK', tagType: 'SYSTEM' }],
      workflows: [],
      contractBalance: {
        assetBalanceId: 7001,
        effectiveDt: '2026-06-26T07:57:52.130Z',
        grossUnpaidReceivableAmt: 1450000,
        liabilityAmt: 1450000,
        averageExposureAmt: 980000,
        overdueDays: 0,
        futureAmt: 250000,
        futureChargesAmt: 15000,
        interestAccrued: 4200,
        arrearsAmt: 0,
        chargingBalance: 1454200,
        accruedDepreciation: 190000,
        totalPrincipal: 1300000,
        totalInterestAccruedAmt: 4200,
        totPricingIntAccruedAmt: 3800,
        grossUnpaidResidualAmt: 320000,
        adjustedBalLessNBV: 12000,
        customAmt00: 0,
        customAmt01: 0,
        customAmt02: 0,
        customAmt03: 0,
        customAmt04: 0,
        customAmt05: 0,
        customAmt06: 0,
        customAmt07: 0,
        customAmt08: 0,
        customAmt09: 0,
        customDt00: '2026-06-26T07:57:52.130Z',
        customDt01: '2026-06-26T07:57:52.130Z',
        customDt02: '2026-06-26T07:57:52.130Z',
        customDt03: '2026-06-26T07:57:52.130Z',
        customDt04: '2026-06-26T07:57:52.130Z',
        amtOverduePrincipal: 0,
        amtDeficiencyOutstandingBalance: 0,
        residualAmt: 0,
        amtPayout: 0,
        amtFuturePayout1: 0,
        amtFuturePayout2: 0,
      },
      flowCalcs: [],
      contractDocuments: [],
      assetInsurance: [],
    },
    paymentStructure: 'STANDARD',
  },
};

function parseBooleanQuery(value: string | undefined): boolean {
  if (!value) {
    return false;
  }

  return value.toLowerCase() === 'true' || value === '1';
}

th.get('/Contracts/:contractId', (c) => {
  const contractIdRaw = c.req.param('contractId');
  const fullDetails = parseBooleanQuery(c.req.query('FullDetails'));
  const isPreview = parseBooleanQuery(c.req.query('IsPreview'));

  const contractId = Number(contractIdRaw);
  if (Number.isNaN(contractId)) {
    return c.json(
      {
        errors: [{ messageId: 'TH-ERR-400', message: 'contractId must be numeric' }],
        warnings: [],
        infos: [],
        data: null,
      },
      400,
    );
  }

  const response = JSON.parse(JSON.stringify(baseContractResponse));
  response.data.contractId = contractId;
  response.data.isDraft = isPreview;

  if (!fullDetails) {
    response.data.contractFull = null;
  }

  return c.json(response);
});

export default th;
